# Generated by Django 6.1 on 2026-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
