# Generated by Django 6.1 on 2026-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_rename_release_data_phone_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
